// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf2N3Dd4edlpcbPd6G9TU5Kwzy5uXkabk',
    appId: '1:830285112633:web:1e0d7a14705bca189534e8',
    messagingSenderId: '830285112633',
    projectId: 'cybeat-flutter',
    authDomain: 'cybeat-flutter.firebaseapp.com',
    storageBucket: 'cybeat-flutter.firebasestorage.app',
    measurementId: 'G-TQ8LFH3HV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIiEF8PmcxZmiOtoTCyq3Ym0LFVr1OSF4',
    appId: '1:830285112633:android:cf761faec48e925d9534e8',
    messagingSenderId: '830285112633',
    projectId: 'cybeat-flutter',
    storageBucket: 'cybeat-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4pook2bElq4SQg6TpI4HFX4EMW9kvKEE',
    appId: '1:830285112633:ios:8cf5e9e22cd699749534e8',
    messagingSenderId: '830285112633',
    projectId: 'cybeat-flutter',
    storageBucket: 'cybeat-flutter.firebasestorage.app',
    iosBundleId: 'com.example.cybeatMusicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4pook2bElq4SQg6TpI4HFX4EMW9kvKEE',
    appId: '1:830285112633:ios:8cf5e9e22cd699749534e8',
    messagingSenderId: '830285112633',
    projectId: 'cybeat-flutter',
    storageBucket: 'cybeat-flutter.firebasestorage.app',
    iosBundleId: 'com.example.cybeatMusicPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf2N3Dd4edlpcbPd6G9TU5Kwzy5uXkabk',
    appId: '1:830285112633:web:a9ddf819d3aef7f89534e8',
    messagingSenderId: '830285112633',
    projectId: 'cybeat-flutter',
    authDomain: 'cybeat-flutter.firebaseapp.com',
    storageBucket: 'cybeat-flutter.firebasestorage.app',
    measurementId: 'G-SN9HSE2XYE',
  );
}
