name: Flutter Build (Staging)

on:
    pull_request:
        branches:
            - staging

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.35.1"
                  channel: stable
                  cache: true

            - name: Get dependencies
              run: flutter pub get

            # STEP BARU UNTUK DEBUGGING
            - name: DEBUG - Show ENV_VARS_DEV content
              run: |
                  echo "--- Start of Secret Content ---"
                  echo "${{ secrets.ENV_VARS_DEV }}"
                  echo "--- End of Secret Content ---"

            # Langkah kunci: Membuat file .env.staging dari secret JSON
            # Runner 'ubuntu-latest' sudah memiliki jq terinstal secara default.
            - name: Generate .env.staging
              run: |
                  echo "${{ secrets.ENV_VARS_STAGE }}" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > .env.staging

            # Verifikasi (opsional, untuk debugging)
            - name: Verify .env.staging content
              run: |
                  echo "File .env.staging berhasil dibuat. Isinya:"
                  cat .env.staging # Hati-hati, ini akan menampilkan KEY tapi GitHub akan menyensor VALUE di log

            - name: Run Analyze
              run: flutter analyze

            - name: Run Tests
              run: flutter test

            - name: Extract version
              id: version
              run: |
                  VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: //;s/\+.*//')
                  echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Build APK (staging/dev)
              run: flutter build apk --debug --split-per-abi

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: cybeat-${{ steps.version.outputs.version }}
                  path: build/app/outputs/flutter-apk/*.apk
