name: Flutter Build (Dev/Staging)

on:
    pull_request:
        branches:
            - staging

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.35.1"
                  channel: stable
                  cache: true

            - name: Get dependencies
              run: flutter pub get

            - name: Run Analyze
              run: flutter analyze

            - name: Run Tests
              run: flutter test

            - name: Extract version
              id: version
              run: |
                  VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: //;s/\+.*//')
                  echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Build APK (staging/dev)
              run: flutter build apk --debug --split-per-abi

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: cybeat-${{ steps.version.outputs.version }}
                  path: build/app/outputs/flutter-apk/*.apk
