name: Lint & Test

on:
    push:
        branches:
            - "feature/*"
            - "fix/*"
            - "optimize/*"
    pull_request:
        branches:
            - develop

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            # Checkout kode dari PR
            - name: Checkout repository
              uses: actions/checkout@v4

            # Setup Java (dibutuhkan Flutter untuk build Android)
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            # Setup Flutter
            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.35.1"
                  channel: "stable"
                  cache: true

            # Ambil dependencies
            - name: Get dependencies
              run: flutter pub get

            # Langkah kunci: Membuat file .env.development dari secret JSON
            # Runner 'ubuntu-latest' sudah memiliki jq terinstal secara default.
            - name: Generate .env.development
              run: |
                  echo "${{ secrets.ENV_VARS_PROD }}" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > .env.development

            # Verifikasi (opsional, untuk debugging)
            - name: Verify .env.development content
              run: |
                  echo "File .env.development berhasil dibuat. Isinya:"
                  cat .env.development # Hati-hati, ini akan menampilkan KEY tapi GitHub akan menyensor VALUE di log

            # Lint (analyze)
            - name: Run flutter analyze
              run: flutter analyze

            # Test
            - name: Run flutter test
              run: flutter test
