name: Lint & Test

on:
    push:
        branches:
            - "feature/*"
            - "fix/*"
            - "optimize/*"
    pull_request:
        branches:
            - develop

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            # Checkout kode dari PR
            - name: Checkout repository
              uses: actions/checkout@v4

            # Setup Java (dibutuhkan Flutter untuk build Android)
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            # Setup Flutter
            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.35.1"
                  channel: "stable"
                  cache: true

            # Ambil dependencies
            - name: Get dependencies
              run: flutter pub get

            # Lint (analyze)
            - name: Run flutter analyze
              run: flutter analyze

            # Test
            - name: Run flutter test
              run: flutter test
